//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeetasWebApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerOrder
    {
        public int CustomerOrderID { get; set; }
        public int SaleID { get; set; }
        public int MenuItemID { get; set; }
        public int Quantity { get; set; }
        public System.DateTime OrderDate { get; set; }
        public System.TimeSpan OrderTime { get; set; }
        public int EmployeeNumber { get; set; }
    
        public virtual MenuItem MenuItem { get; set; }
    }
}
